name: Build iOS Production
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Build iOS App
    type: build
    params:
      platform: ios
      profile: production
